---
name: build

on:
  workflow_dispatch:
  push:
    tags: ["v*"]
    paths-ignore:
      - README.md

jobs:
  release:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Vagrant base box update
        run: vagrant box update

      - name: Vagrant scp plugin
        run: vagrant plugin install vagrant-scp

      - name: Bring up the VM
        run: vagrant up --provision
        env:
          REV: v5.4.2

      - name: Copy zcashd from vbox
        run: vagrant scp :zcash/src/zcashd .

      - name: Destroy the VM
        run: vagrant destroy -f

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./zcashd
