---
name: build

on:
  workflow_dispatch:
  push:
    tags: ["v*"]
    paths-ignore:
      - README.md

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        env:
          TAG: v5.8.0
        run: |
          ./zcash-build.sh $TAG

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./zcash/src/zcashd
